services:
  service-node:
    container_name: service-node
    build:
      context: .
      target: base
    env_file: .env
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
